# NumPy

*  Массивы  *

In [7]:
print("Hello, Jupyter!")

Hello, Jupyter!


In [6]:
def func_1(arg_1, arg_2):
    print(arg_1+arg_2)
    
func_1(10, 20)

30


In [8]:
# вывод без print
a = 10

a + 3
a + 4

14

In [9]:
# вывод с print

print(a + 2)
print(a + 5)

12
15


In [10]:
import numpy as np

In [11]:
# создание массивов

my_list = [4, 2, 1, 5, 7]
my_list

[4, 2, 1, 5, 7]

In [12]:
# создание одномерного массива (вектор)
np.array(my_list)



array([4, 2, 1, 5, 7])

In [13]:
# создание нь-мерного массива (матрица)
my_list = [[10,20,30],[40,50,60]]
np.array(my_list)

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
# создание массива из нулей
z = np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [15]:
# массив из целочисленных значений
z.astype("int")

array([0, 0, 0, 0, 0])

In [18]:
# создание 2-мерного массива из нулей
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [19]:
# создание нь-мерно массива из единиц
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# 1-мерный массив со значениями в линейной последовательности
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [25]:
# из 1-мерного массива можно сделать 2-мерный
# форма 2-мерного массива должна соответствовать длине 1-мерного масиива
arr = np.arange(10)
arr.reshape((2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [27]:
arr.reshape((3,3))

ValueError: cannot reshape array of size 10 into shape (3,3)

In [28]:
# 1-массив формой 5
#  со случайными значениями из равномерного распределния 
# в диапазоне от 0 до 1
np.random.random(5)

array([0.52911884, 0.14599716, 0.05350363, 0.35987696, 0.36248318])

In [30]:
# 2-мерный массив формой 3*5
np.random.random((3,5))

array([[0.11122419, 0.05506919, 0.30364062, 0.71874448, 0.16332969],
       [0.11522355, 0.32987719, 0.51843054, 0.78368974, 0.28312449],
       [0.4762049 , 0.09055964, 0.8854156 , 0.7373849 , 0.42842995]])